version: '3.8'

services:
  test_runner:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pytest_runner
    container_name: pytest_runner_works
    environment:
      ENV: dev  
      PYTHONUNBUFFERED: 1  
    volumes:
      - ./:/tests_project/  
    working_dir: /tests_project 
